### ISSUE TITLE
wrong display of formula 

### ISSUE THREAD

**Issue by shony666** [cosmocode/dokuwiki-plugin-mathpublish#1]
the following two examples shouldn't produce the same output

```
<m>E/((L*COS(I)*SIN(I+H))/J*K*K)</m>

<m>E/((L*COS(I)*SIN(I+H))/(J*K*K))</m>
```

**Comment by splitbrain** [comment]
They are producing different output for me:

![2016-09-02-211135_266x216_scrot](https://cloud.githubusercontent.com/assets/86426/18215516/eb28dd54-7151-11e6-888c-6ac8e07338bf.png)
