### ISSUE TITLE
Wrong call to _msg function

### ISSUE THREAD

**Issue by Id2ndR** [cosmocode/dokuwiki-plugin-mathpublish#2]
In class syntax_plugin_mathpublish, function _requirements_ok, $this->msg should be $this->_msg.
Otherwise you got this in error.log : PHP Fatal error:  Call
 to undefined method syntax_plugin_mathpublish::msg() in /var/www/ [..] /dokuwiki-2012-01-25a/lib/plugins/mathpublish/syntax.php on line 135, referer: [..]

Then I installed php5-gd ;).

**Comment by splitbrain** [comment]
fixed
